[package]
name = "guest_code_for_zk_proof"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
json = "0.12.4"
json-core = {path = "../../core"}
risc0-zkvm = { version = "1.2.4", default-features = false, features = ['std'] }
sha2 = "0.10.8"
